"use client"
import "../globals.css";
import { inter } from "@/lib/fonts";
import NextNProgress from 'nextjs-progressbar';

/*export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}*/


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
            <NextNProgress color="#29D" startPosition={0.3} stopDelayMs={200} height={3} showOnShallow={true} />

      <body  className = {`bg-gray-950 text-gray-300 ${inter.className}`}>{children}</body>
    </html>
  )
}
